Overworked packages

diff --git a/sbp-admin/admin.install b/sbp-admin/admin.install
--- a/sbp-admin/admin.install
+++ b/sbp-admin/admin.install
@@ -1,42 +1,59 @@
 # Maintained by sbp
+prestr='sbp-admin'
+
+systemd_services() {
+  if [ "${1}" = 'enable' ] ; then     action='enable'  ; prstrn='Enabling'
+  elif [ "${1}" = 'disable' ] ; then  action='disable' ; prstrn='Disabling'
+  elif [ -z "${1}" ] ; then           action='enable'  ; prstrn='Enabling'
+  else
+    echo "Invalid action type"
+    exit 1
+  fi
+  echo '['"${prestr}"']==> '${prstrn}' systemd services!'
+  # Services
+  echo '['"${prestr}"']==> Enabling cron.'
+  /usr/bin/systemctl "${action}" fcron.service
+  echo '['"${prestr}"']==> Enabling MCE monitoring'
+  /usr/bin/systemctl enable rasdaemon.service
+  /usr/bin/systemctl enable ras-mc-ctl.service
+
+  echo '['"${prestr}"']==> '"${prstrn}"' systemd services, done!'
+}
+
 post_install() {
-    echo '[sbp-admin]==> Installing meta package...'
+  echo '['"${prestr}"']==> Installing meta package...'
 
-    # Timezone
-    echo '[sbp-admin]==> Setting local time settings.'
-    /usr/bin/timedatectl set-ntp true
-    /usr/bin/hwclock --systohc
+  # Timezone
+  echo '['"${prestr}"']==> Setting local time settings.'
+  /usr/bin/timedatectl set-ntp true
+  /usr/bin/hwclock --systohc
 
-    # Services
-    echo '[sbp-admin]==> Enabling cron.'
-    /usr/bin/systemctl enable fcron.service
+  # Services
+  systemd_services enable
 
-    echo '[sbp-admin]==> Enabling MCE monitoring'
-    /usr/bin/systemctl enable rasdaemon.service
-    /usr/bin/systemctl enable ras-mc-ctl.service
 
-    echo '[sbp-admin]==> Installation done!'
-    post_upgrade
+  echo '['"${prestr}"']==> Installation done!'
+  post_upgrade
 }
 
 post_upgrade() {
-    echo '[sbp-admin]==> Upgrading meta package...'
-    echo '[sbp-admin]==> Upgrade done!'
+  echo '['"${prestr}"']==> Upgrading meta package...'
+  echo '['"${prestr}"']==> Upgrade done!'
 }
 
 post_remove() {
-    echo '[sbp-admin]==> Uninstalling meta package...'
+  echo '['"${prestr}"']==> Uninstalling meta package...'
 
-    # Services
-    echo '[sbp-admin]==> Disabling CPU scaling manager.'
-    /usr/bin/systemctl disable cpupower.service
+  # Services
+  echo '['"${prestr}"']==> Disabling CPU scaling manager.'
+  /usr/bin/systemctl disable cpupower.service
 
-    echo '[sbp-admin]==> Disbling cron.'
-    /usr/bin/systemctl disable fcron.service
+  echo '['"${prestr}"']==> Disbling cron.'
+  /usr/bin/systemctl disable fcron.service
 
-    echo '[sbp-admin]==> Disbling MCE monitoring'
-    /usr/bin/systemctl disable rasdaemon.service
-    /usr/bin/systemctl disable ras-mc-ctl.service
+  echo '['"${prestr}"']==> Disbling MCE monitoring'
+  /usr/bin/systemctl disable rasdaemon.service
+  /usr/bin/systemctl disable ras-mc-ctl.service
 
-    echo '[sbp-admin]==> Unistallation done!'
+  echo '['"${prestr}"']==> Unistallation done!'
 }
diff --git a/sbp-fs/fs.install b/sbp-fs/fs.install
--- a/sbp-fs/fs.install
+++ b/sbp-fs/fs.install
@@ -1,34 +1,41 @@
 # Maintained by sbp
+prestr='sbp-fs'
+
+systemd_services() {
+  if [ "${1}" = 'enable' ] ; then     action='enable'  ; prstrn='Enabling'
+  elif [ "${1}" = 'disable' ] ; then  action='disable' ; prstrn='Disabling'
+  elif [ -z "${1}" ] ; then           action='enable'  ; prstrn='Enabling'
+  else
+  echo "Invalid action type"
+  exit 1
+  fi
+  echo '['"${prestr}"']==> '${prstrn}' systemd services!'
+  # Services
+  echo '['"${prestr}"']==> Enabling periodic trimming.'
+  /usr/bin/systemctl enable fstrim.timer
+  echo '['"${prestr}"']==> Enabling snapper snapshots.'
+  /usr/bin/systemctl enable snapper-cleanup.timer
+  /usr/bin/systemctl enable snapper-timeline.timer
+
+  echo '['"${prestr}"']==> '"${prstrn}"' systemd services, done!'
+}
 
 post_install() {
-    echo '[sbp-fs]==> Installing meta package...'
+  echo '['"${prestr}"']==> Installing meta package...'
+  systemd_services enable
 
-    # Services
-    echo '[sbp-fs]==> Enabling periodic trimming.'
-    /usr/bin/systemctl enable fstrim.timer
-
-    echo '[sbp-fs]==> Enabling snapper snapshots.'
-    /usr/bin/systemctl enable snapper-cleanup.timer
-    /usr/bin/systemctl enable snapper-timeline.timer
-
-    echo '[sbp-fs]==> Installation done!'
-    post_upgrade
+  echo '['"${prestr}"']==> Installation done!'
+  post_upgrade
 }
 
 post_upgrade() {
-    echo '[sbp-fs]==> Upgrading meta package...'
-    echo '[sbp-fs]==> Upgrade done!'
+  echo '['"${prestr}"']==> Upgrading meta package...'
+  systemd_services enable
+  echo '['"${prestr}"']==> Upgrade done!'
 }
 
 post_remove() {
-    echo '[sbp-fs]==> Uninstalling meta package...'
-
-    echo '[sbp-fs]==> Disabling periodic trimming.'
-    /usr/bin/systemctl disable fstrim.timer
-
-    echo '[sbp-fs]==> Disabling snapper snapshots.'
-    /usr/bin/systemctl disable snapper-cleanup.timer
-    /usr/bin/systemctl disable snapper-timeline.timer
-
-    echo '[sbp-fs]==> Uninstallation done!'
+  echo '['"${prestr}"']==> Uninstalling meta package...'
+  systemd_services disable
+  echo '['"${prestr}"']==> Uninstallation done!'
 }
diff --git a/sbp-gui/gui.install b/sbp-gui/gui.install
--- a/sbp-gui/gui.install
+++ b/sbp-gui/gui.install
@@ -1,27 +1,37 @@
 # Maintained by sbp
+prestr='sbp-workstation'
+
+systemd_services() {
+  if [ "${1}" = 'enable' ] ; then     action='enable'  ; prstrn='Enabling'
+  elif [ "${1}" = 'disable' ] ; then  action='disable' ; prstrn='Disabling'
+  elif [ -z "${1}" ] ; then           action='enable'  ; prstrn='Enabling'
+  else
+  echo "Invalid action type"
+  exit 1
+  fi
+  echo '['"${prestr}"']==> '${prstrn}' systemd services!'
+  # Services
+  echo '['"${prestr}"']==> '"${prstrn}"' Network UPS tools'
+  /usr/bin/systemctl "${action}" sddm.service
+  echo '['"${prestr}"']==> '"${prstrn}"' systemd services, done!'
+}
 
 post_install() {
-    echo '[sbp-gui]==> Installing meta package...'
-
-    # Services
-    echo '[sbp-gui]==> Enabling graphical login. (SDDM)'
-    /usr/bin/systemctl enable sddm.service
-
-    echo '[sbp-gui]==> Installation done!'
-    post_upgrade
+  echo '['"${prestr}"']==> Installing meta package...'
+  # Services
+  systemd_services enable
+  echo '['"${prestr}"']==> Installation done!'
+  post_upgrade
 }
 
 post_upgrade() {
-    echo '[sbp-gui]==> Upgrading meta package...'
-    echo '[sbp-gui]==> Upgrade done!'
+  echo '['"${prestr}"']==> Upgrading meta package...'
+  systemd_services enable
+  echo '['"${prestr}"']==> Upgrade done!'
 }
 
 post_remove() {
-    echo '[sbp-gui]==> Uninstalling meta package...'
-
-    # Services
-    echo '[sbp-gui]==> Disabling graphical login. (SDDM)'
-    /usr/bin/systemctl disable sddm.service
-    
-    echo '[sbp-gui]==> Uninstallation done!'
+  echo '['"${prestr}"']==> Uninstalling meta package...'
+  systemd_services disable 
+  echo '['"${prestr}"']==> Uninstallation done!'
 }
diff --git a/sbp-hardware/hardware.install b/sbp-hardware/hardware.install
--- a/sbp-hardware/hardware.install
+++ b/sbp-hardware/hardware.install
@@ -6,8 +6,8 @@ systemd_services() {
   elif [ "${1}" = 'disable' ] ; then  action='disable' ; prstrn='Disabling'
   elif [ -z "${1}" ] ; then           action='enable'  ; prstrn='Enabling'
   else
-    echo "Invalid action type"
-    exit 1
+  echo "Invalid action type"
+  exit 1
   fi
   echo '['"${prestr}"']==> '${prstrn}' systemd services!'
   # Services
@@ -24,19 +24,19 @@ systemd_services() {
 }
 
 post_install() {
-    echo '['"${prestr}"']==> Installing meta package...'
-    systemd_services enable
-    echo '['"${prestr}"']==> Installation done!'
+  echo '['"${prestr}"']==> Installing meta package...'
+  systemd_services enable
+  echo '['"${prestr}"']==> Installation done!'
 }
 
 post_upgrade() {
-    echo '['"${prestr}"']==> Upgrading meta package...'
-    systemd_services enable
-    echo '['"${prestr}"']==> Upgrade done!'
+  echo '['"${prestr}"']==> Upgrading meta package...'
+  systemd_services enable
+  echo '['"${prestr}"']==> Upgrade done!'
 }
 
 post_remove() {
-    echo '['"${prestr}"']==> Uninstalling meta package...'
-    systemd_services disable
-    echo '['"${prestr}"']==> Uninstallation done!'
+  echo '['"${prestr}"']==> Uninstalling meta package...'
+  systemd_services disable
+  echo '['"${prestr}"']==> Uninstallation done!'
 }
diff --git a/sbp-laptop/laptop.install b/sbp-laptop/laptop.install
--- a/sbp-laptop/laptop.install
+++ b/sbp-laptop/laptop.install
@@ -1,53 +1,81 @@
 # Maintained by sbp
+pkggroups=('sys')
+prestr='sbp-laptop'
+
+systemd_services() {
+  if [ "${1}" = 'enable' ] ; then   action='enable'  ; prstrn='Enabling'
+  elif [ "${1}" = 'disable' ] ; then  action='disable' ; prstrn='Disabling'
+  elif [ -z "${1}" ] ; then       action='enable'  ; prstrn='Enabling'
+  else
+  echo "Invalid action type"
+  exit 1
+  fi
+  echo '['"${prestr}"']==> '"${prstrn}"' systemd services!'
+  # Services
+  echo '['"${prestr}"']==> '"${prstrn}"' CUPS daemon.'
+  /usr/bin/systemctl "${action}" org.cups.cupsd.service
+  echo '['"${prestr}"']==> Enabling wifi.'
+  /usr/bin/systemctl enable iwd.service
+  echo '['"${prestr}"']==> Enabling TLP.'
+  /usr/bin/systemctl enable tlp.service
+  echo '['"${prestr}"']==> Enabling System76 services.'
+  /usr/bin/systemctl enable system76.service
+  /usr/bin/systemctl enable system76-firmware-daemon.service
+  echo '['"${prestr}"']==> Enabling Trezor for bitcoin wallet.'
+  /usr/bin/systemctl enable trezord.service
+
+  echo '['"${prestr}"']==> '"${prstrn}"' systemd services, done!'
+}
+
 pre_install() {
-    echo '[sbp-cmp]==> Preparing for meta package...'
-    if [ -e '/etc/fstab' ] ; then
-        echo '[sbp-cmp]==> Moving /etc/fstab away.'
-        mv '/etc/fstab' '/etc/fstab.system'
-    fi
-    if [ -e '/etc/crypttab' ] ; then
-        echo '[sbp-cmp]==> Moving /etc/crypttab away.'
-        mv '/etc/crypttab' '/etc/crypttab.system'
-    fi
-    if [ -e '/etc/mkinitcpio.conf' ] ; then
-        echo '[sbp-cmp]==> Moving /etc/mkinitcpio.conf away.'
-        mv '/etc/mkinitcpio.conf' '/etc/mkinitcpio.system'
-    fi
-    echo '[sbp-cmp]==> Preperations done!'
+  echo '[sbp-cmp]==> Preparing for meta package...'
+  if [ -e '/etc/fstab' ] ; then
+    echo '[sbp-cmp]==> Moving /etc/fstab away.'
+    mv '/etc/fstab' '/etc/fstab.system'
+  fi
+  if [ -e '/etc/crypttab' ] ; then
+    echo '[sbp-cmp]==> Moving /etc/crypttab away.'
+    mv '/etc/crypttab' '/etc/crypttab.system'
+  fi
+  if [ -e '/etc/mkinitcpio.conf' ] ; then
+    echo '[sbp-cmp]==> Moving /etc/mkinitcpio.conf away.'
+    mv '/etc/mkinitcpio.conf' '/etc/mkinitcpio.system'
+  fi
+  echo '[sbp-cmp]==> Preperations done!'
 }
 
 post_install() {
-    echo '[sbp-laptop]==> Installing meta package...'
-
-    # Services
-    echo '[sbp-laptop]==> Enabling wifi.'
-    /usr/bin/systemctl enable iwd.service
-
-    echo '[sbp-laptop]==> Enabling System76 services.'
-    /usr/bin/systemctl enable system76.service
-    /usr/bin/systemctl enable system76-firmware-daemon.service
-
-    # End message
-    echo '[sbp-laptop]==> Installation done!'
-    post_upgrade
+  echo '['"${prestr}"']==> Installing meta package...'
+  systemd_services enable
+  # Adding user to the groups
+  echo '['"${prestr}"']==> Adding user sbp to sys group (cups).'
+  for grp in "${pkggroups[@]}" ; do
+    /bin/gpasswd --add sbp "${grp}"
+  done
+  # End message
+  echo '['"${prestr}"']==> Installation done!'
+  post_upgrade
 }
 
 post_upgrade() {
-    echo '[sbp-laptop]==> Upgrading...'
-    echo '[sbp-laptop]==> Upgrade done!'
+  echo '['"${prestr}"']==> Upgrading...'
+  systemd_services enable
+  # Adding user to the groups
+  echo '['"${prestr}"']==> Adding user sbp to sys group (cups).'
+  for grp in "${pkggroups[@]}" ; do
+    /bin/gpasswd --add sbp "${grp}"
+  done
+  echo '['"${prestr}"']==> Upgrade done!'
 }
 
 post_remove() {
-    echo '[sbp-laptop]==> Uninstalling meta package...'
-
-    # Services
-    echo '[sbp-laptop]==> Disabling wifi.'
-    /usr/bin/systemctl disable iwd.service
-
-    echo '[sbp-laptop]==> Disabling System76 services.'
-    /usr/bin/systemctl disable system76.service
-    /usr/bin/systemctl disable system76-firmware-daemon.service
-
-    # End message
-    echo '[sbp-laptop]==> Uninstallation done!'
+  echo '['"${prestr}"']==> Uninstalling meta package...'
+  systemd_services disable
+  # Adding user to the groups
+  echo '['"${prestr}"']==> Removing user sbp to sys group (cups).'
+  for grp in "${pkggroups[@]}" ; do
+    /bin/gpasswd --delete sbp "${grp}"
+  done
+  # End message
+  echo '['"${prestr}"']==> Uninstallation done!'
 }
diff --git a/sbp-server/server.install b/sbp-server/server.install
--- a/sbp-server/server.install
+++ b/sbp-server/server.install
@@ -1,19 +1,67 @@
 # Maintained by sbp
+prestr='sbp-server'
+
+systemd_services() {
+  if [ "${1}" = 'enable' ] ; then     action='enable'  ; prstrn='Enabling'
+  elif [ "${1}" = 'disable' ] ; then  action='disable' ; prstrn='Disabling'
+  elif [ -z "${1}" ] ; then           action='enable'  ; prstrn='Enabling'
+  else
+    echo "Invalid action type"
+    exit 1
+  fi
+  echo '['"${prestr}"']==> '${prstrn}' systemd services!'
+  # Services
+  echo '['"${prestr}"']==> '"${prstrn}"' wifi.'
+  /usr/bin/systemctl "${action}" iwd.service
+  echo '['"${prestr}"']==> '"${prstrn}"' NFS server.'
+  /bin/systemctl "${action}" nfs-server.service
+  echo '['"${prestr}"']==> '"${prstrn}"' MariaDB.'
+  /bin/systemctl "${action}" mariadb.service
+  echo '['"${prestr}"']==> '"${prstrn}"' SSH access.'
+  /bin/systemctl "${action}" sshd.service
+
+  echo '['"${prestr}"']==> '"${prstrn}"' systemd services, done!'
+}
+
+pre_install() {
+    echo '[sbp-cmp]==> Preparing for meta package...'
+    if [ -e '/etc/fstab' ] ; then
+        echo '[sbp-cmp]==> Moving /etc/fstab away.'
+        mv '/etc/fstab' '/etc/fstab.system'
+    fi
+    if [ -e '/etc/crypttab' ] ; then
+        echo '[sbp-cmp]==> Moving /etc/crypttab away.'
+        mv '/etc/crypttab' '/etc/crypttab.system'
+    fi
+    if [ -e '/etc/mkinitcpio.conf' ] ; then
+        echo '[sbp-cmp]==> Moving /etc/mkinitcpio.conf away.'
+        mv '/etc/mkinitcpio.conf' '/etc/mkinitcpio.system'
+    fi
+    echo '[sbp-cmp]==> Preperations done!'
+}
+
 post_install() {
-
-    echo '[sbp-cmp-server]==> Installing meta package . . .'
-
-    # Do hostname
-    echo '[sbp-cmp-server]==> Doing hosts . . .'
-    echo '127.0.0.1 localhost' >  /etc/hosts
-    echo '::1       localhost' >> /etc/hosts
-    echo '127.0.1.1 sbp-server.localdomain sbp-server' >> /etc/hosts
-
-    echo '[sbp-cmp-server]==> Installation done! Check log for errors.'
-    post_upgrade
+    echo '['"${prestr}"']==> Installing meta package . . .'
+    systemd_services enable
+    if [ -d '/var/lib/mariadb' ] ; then
+      echo '['"${prestr}"']==> Disabling CoW on MariaDB...'
+      chattr +C '/var/lib/mariadb'
+    fi
+    echo '['"${prestr}"']==> Installation done!'
 }
 
 post_upgrade() {
-    echo '[sbp-cmp-server]==> Upgrading . . .'
-    echo '[sbp-cmp-server]==> Nothing to do.'
+    echo '['"${prestr}"']==> Upgrading meta package...'
+    systemd_services enable
+    if [ -d '/var/lib/mariadb' ] ; then
+      echo '['"${prestr}"']==> Disabling CoW on MariaDB...'
+      chattr +C '/var/lib/mariadb'
+    fi
+    echo '['"${prestr}"']==> Upgrade done!'
+}
+
+post_remove() {
+    echo '['"${prestr}"']==> Uninstalling meta package...'
+    systemd_services disable
+    echo '['"${prestr}"']==> Uninstallation done!'
 }
diff --git a/sbp-virtual/virtual.install b/sbp-virtual/virtual.install
--- a/sbp-virtual/virtual.install
+++ b/sbp-virtual/virtual.install
@@ -1,38 +1,59 @@
 # Maintained by sbp
+pkggroups=('kvm' 'libvirt')
+prestr='sbp-virtual'
+
+systemd_services() {
+  if [ "${1}" = 'enable' ] ; then   action='enable'  ; prstrn='Enabling'
+  elif [ "${1}" = 'disable' ] ; then  action='disable' ; prstrn='Disabling'
+  elif [ -z "${1}" ] ; then       action='enable'  ; prstrn='Enabling'
+  else
+  echo "Invalid action type"
+  exit 1
+  fi
+  echo '['"${prestr}"']==> '"${prstrn}"' systemd services!'
+  # Services
+  echo '['"${prestr}"']==> Enabling libvirt services.'
+  /usr/bin/systemctl enable libvirtd.service
+  /usr/bin/systemctl enable virtlogd.service
+
+  echo '['"${prestr}"']==> '"${prstrn}"' systemd services, done!'
+}
 
 post_install() {
-    echo '[sbp-virtual]==> Installing meta package...'
-
-    # Add user to kvm
-    echo '[sbp-virtual]==> Adding user to kvm group'
-    if [ "$(getent passwd | grep -c '^sbp')" == "0" ] ; then
-        gpasswd --add sbp kvm
-        gpasswd --add sbp libvirt
-    else
-        echo '[sbp-virtual]==> User sbp is missing!'
-    fi
-
-    # Services
-    echo '[sbp-virtual]==> Enabling libvirt services.'
-    /usr/bin/systemctl enable libvirtd.service
-    /usr/bin/systemctl enable virtlogd.service
-
-    echo '[sbp-virtual]==> Installation done!'
+  echo '['"${prestr}"']==> Installing meta package...'
+  # Enabling systemd services
+  systemd_services enable
+  # Adding user to the groups
+  echo '['"${prestr}"']==> Adding user sbp to sys group (cups).'
+  for grp in "${pkggroups[@]}" ; do
+    /bin/gpasswd --add sbp "${grp}"
+  done
+  
+  echo '['"${prestr}"']==> Installation done!'
 }
 
 post_upgrade() {
-    echo '[sbp-virtual]==> Upgrading meta package...'
-    echo '[sbp-virtual]==> Upgrade done!'
+  echo '['"${prestr}"']==> Upgrading meta package...'
+  # Enabling systemd services
+  systemd_services enable
+  # Adding user to the groups
+  echo '['"${prestr}"']==> Adding user sbp to sys group (cups).'
+  for grp in "${pkggroups[@]}" ; do
+    /bin/gpasswd --add sbp "${grp}"
+  done
+  echo '['"${prestr}"']==> Upgrade done!'
 }
 
 post_uninstall() {
-    echo '[sbp-virtual]==> Uninstalling meta package...'
+  echo '['"${prestr}"']==> Uninstalling meta package...'
+  # Enabling systemd services
+  systemd_services disable
+  # Adding user to the groups
+  echo '['"${prestr}"']==> Adding user sbp to sys group (cups).'
+  for grp in "${pkggroups[@]}" ; do
+    /bin/gpasswd --delete sbp "${grp}"
+  done
 
-    # Services
-    echo '[sbp-virtual]==> Disabling required services'
-    /usr/bin/systemctl disable libvirtd.service
-    /usr/bin/systemctl disable virtlogd.service
-
-    echo '[sbp-virtual]==> Uninstallation done!'
+  echo '['"${prestr}"']==> Uninstallation done!'
 }
 
