Overhaul

diff --git a/sbp-seedbox/seedbox.install b/sbp-seedbox/seedbox.install
--- a/sbp-seedbox/seedbox.install
+++ b/sbp-seedbox/seedbox.install
@@ -2,49 +2,66 @@
 prestr='sbp-seedbox'
 
 systemd_services() {
-  if [ "${1}" = 'enable' ] ; then   action='enable'  ; prstrn='Enabling'
+  if [ "${1}" = 'enable' ] ; then     action='enable'  ; prstrn='Enabling'
   elif [ "${1}" = 'disable' ] ; then  action='disable' ; prstrn='Disabling'
-  elif [ -z "${1}" ] ; then       action='enable'  ; prstrn='Enabling'
+  elif [ -z "${1}" ] ; then           action='enable'  ; prstrn='Enabling'
   else
-  echo "Invalid action type"
-  exit 1
+    echo "Invalid action type"
+    exit 1
   fi
   echo '['"${prestr}"']==> '${prstrn}' systemd services!'
   # Services
   echo '['"${prestr}"']==> '"${prstrn}"' Network Manager.'
   /usr/bin/systemctl "${action}" NetworkManager.service
+  
   echo '['"${prestr}"']==> '"${prstrn}"' QEMU Guest Agent.'
   /usr/bin/systemctl "${action}" qemu-ga.service
+  
   echo '['"${prestr}"']==> '"${prstrn}"' Mullvad VPN.'
   /usr/bin/systemctl "${action}" mullvad-daemon.service
+  
   echo '['"${prestr}"']==> '"${prstrn}"' Deluge BitTorrent daemon.'
   /usr/bin/systemctl "${action}" deluged.service
+  
   echo '['"${prestr}"']==> '"${prstrn}"' Zeroconf networking'
   /usr/bin/systemctl "${action}" avahi-daemon.service
+  
   echo '['"${prestr}"']==> '"${prstrn}"' NFS server.'
   /bin/systemctl "${action}" nfs-server.service
+  
   echo '['"${prestr}"']==> '"${prstrn}"' systemd services, done!'
 }
 
 post_install() {
   echo '['"${prestr}"']==> Installing meta package...'
   # Change root shell to zsh
+
   echo '['"${prestr}"']==> Changing shell for root user.'
   /bin/chsh --shell /bin/zsh root
 
   systemd_services enable 
+
+  echo '['"${prestr}"']==> Creating directories for deluge.'
+  mkdir -p /srv/deluge/{Downloads,Completed,Torrents}
+  chown deluge:deluge /srv/deluge/{Downloads,Completed,Torrents}
+  chmod 755 /srv/deluge/{Downloads,Completed,Torrents}
+  
   echo '['"${prestr}"']==> Installation done!'
   post_upgrade
 }
 
 post_upgrade() {
   echo '['"${prestr}"']==> Upgrading meta package...'
+  
   systemd_services enable
+  
   echo '['"${prestr}"']==> Upgrade done!'
 }
 
 post_remove() {
   echo '['"${prestr}"']==> Uninstalling meta package...'
+
   systemd_services disable
+  
   echo '['"${prestr}"']==> Uninstallation done!'
 }
diff --git a/sbp-workstation/workstation.install b/sbp-workstation/workstation.install
--- a/sbp-workstation/workstation.install
+++ b/sbp-workstation/workstation.install
@@ -1,23 +1,20 @@
 # Maintained by sbp
-pkggroups=('sys')
 prestr='sbp-workstation'
 
 systemd_services() {
-  if [ "${1}" = 'enable' ] ; then   action='enable'  ; prstrn='Enabling'
+  if [ "${1}" = 'enable' ] ;    then  action='enable'  ; prstrn='Enabling'
   elif [ "${1}" = 'disable' ] ; then  action='disable' ; prstrn='Disabling'
-  elif [ -z "${1}" ] ; then       action='enable'  ; prstrn='Enabling'
+  elif [ -z "${1}" ] ;          then  action='enable'  ; prstrn='Enabling'
   else
-  echo "Invalid action type"
-  exit 1
+    echo "Invalid action type"
+    exit 1
   fi
   echo '['"${prestr}"']==> '${prstrn}' systemd services!'
   # Services
   echo '['"${prestr}"']==> '"${prstrn}"' Network UPS tools'
   /usr/bin/systemctl "${action}" nut-server.service
   /usr/bin/systemctl "${action}" nut-monitor.service
-  echo '['"${prestr}"']==> '"${prstrn}"' CUPS daemon.'
-  /usr/bin/systemctl "${action}" org.cups.cupsd.service
-  echo '['"${prestr}"']==> '"${prstrn}"' SSH access'
+  echo '['"${prestr}"']==> '"${prstrn}"' Enable SSH access'
   /usr/bin/systemctl "${action}" sshd.service
 
   echo '['"${prestr}"']==> '"${prstrn}"' systemd services, done!'
@@ -43,11 +40,6 @@ pre_install() {
 post_install() {
   echo '['"${prestr}"']==> Installing meta package...'
   systemd_services enable
-  # Adding user to the groups
-  echo '['"${prestr}"']==> Adding user sbp to sys group (cups).'
-  for grp in "${pkggroups[@]}" ; do
-    /bin/gpasswd --add sbp "${grp}"
-  done
   echo '['"${prestr}"']==> Installation done!'
   post_upgrade
 }
@@ -55,21 +47,11 @@ post_install() {
 post_upgrade() {
   echo '['"${prestr}"']==> Upgrading meta package ...'
   systemd_services enable
-  # Adding user to the groups
-  echo '['"${prestr}"']==> Adding user sbp to sys group (cups).'
-  for grp in "${pkggroups[@]}" ; do
-    /bin/gpasswd --add sbp "${grp}"
-  done
   echo '['"${prestr}"']==> Upgrade done!'
 }
 
 post_remove() {
   echo '['"${prestr}"']==> Uninstalling meta package...'
   systemd_services disable
-  # Adding user to the groups
-  echo '['"${prestr}"']==> Adding user sbp to sys group (cups).'
-  for grp in "${pkggroups[@]}" ; do
-    /bin/gpasswd --delete sbp "${grp}"
-  done
   echo '['"${prestr}"']==> Uninstallation done!'
 }
